import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import AuthProvider from '@/app/providers/AuthProvider';
import ConfirmDialog from '@/app/components/common/ConfirmDialog';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LoginLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfirmDialog/>
        {children}
      </body>
    </html>
  )
}

console.log('Layout for login');