const AirlineCodeList = [
  { carrierCode: 'SU', airline: 'SU/AFL: Aeroflot Russian Airlines' },
  { carrierCode: 'LD', airline: 'LD/AHK: AHK Air Hong Kong Ltd.' },
  { carrierCode: 'AA', airline: 'AA/AAL: American Airlines' },
  { carrierCode: 'AZ', airline: 'AZ/AZA: Alitalia-Compagnia Aerea Italiana SP' },
  { carrierCode: 'SB', airline: 'SB/ACI: Air Caledonie International' },
  { carrierCode: 'AC', airline: 'AC/ACA: Air Canada' },
  { carrierCode: 'CA', airline: 'CA/CCA: Air China Ltd.' },
  { carrierCode: 'AF', airline: 'AF/AFR: Air France' },
  { carrierCode: 'NZ', airline: 'NZ/ANZ: Air New Zealand Ltd.' },
  { carrierCode: 'AI', airline: 'AI/AIC: Air India Ltd.' },
  { carrierCode: 'EL', airline: 'EL/ANK: Air Nippon Co. Ltd.' },
  { carrierCode: 'PX', airline: 'PX/ANG: Air Niugini Pty. Ltd.' },
  { carrierCode: 'FJ', airline: 'FJ/FJI: Air Pacific' },
  { carrierCode: 'TN', airline: 'TN/THT: Air Tahiti Nui' },
  { carrierCode: 'AM', airline: 'AM/AMX: Aeromexico' },
  { carrierCode: 'NH', airline: 'NH/ANA: All Nippon Airways Co. Ltd.' },
  { carrierCode: 'G4', airline: 'G4/AAY: Allegiant Air' },
  { carrierCode: 'OZ', airline: 'OZ/AAR: Asiana Airlines Inc.' },
  { carrierCode: 'OS', airline: 'OS/AUA: Austrian Airlines AG' },
  { carrierCode: 'XP', airline: 'XP/VXP: Avelo Airlines' },
  { carrierCode: 'MX', airline: 'MX/MXY: Breeze Airways' },
  { carrierCode: 'BA', airline: 'BA/BAW: British Airways PLC' },
  { carrierCode: 'CX', airline: 'CX/CPA: Cathay Pacific Airways Ltd.' },
  { carrierCode: 'CV', airline: 'CV/CLX: Cargolux Airlines Int\'l SA' },
  { carrierCode: 'CI', airline: 'CI/CAL: China Airlines Ltd.' },
  { carrierCode: 'MU', airline: 'MU/CES: China Eastern Airlines' },
  { carrierCode: 'CZ', airline: 'CZ/CSN: China Southern Airlines' },
  { carrierCode: 'CO', airline: 'CO/COA: Continental Airlines, Inc.' },
  { carrierCode: 'H8', airline: 'H8/KHB: Dalavia Far East Airways' },
  { carrierCode: 'DL', airline: 'DL/DAL: Delta Air Lines, Inc.' },
  { carrierCode: '2D', airline: '2D/EAL: Eastern Airlines' },
  { carrierCode: 'MS', airline: 'MS/MSR: Egyptair' },
  { carrierCode: 'EK', airline: 'EK/UAE: Emirates Sky Cargo' },
  { carrierCode: 'BR', airline: 'BR/EVA: Eva Airways Corp.' },
  { carrierCode: 'FX', airline: 'FX/FDX: FedEX' },
  { carrierCode: 'AY', airline: 'AY/FIN: Finnair O/Y' },
  { carrierCode: 'F9', airline: 'F9/FFT: Frontier Airlines' },
  { carrierCode: 'GA', airline: 'GA/GIA: Garuda Indonesia' },
  { carrierCode: 'HA', airline: 'HA/HAL: Hawaiian Airlines' },
  { carrierCode: 'KA', airline: 'HK/HAD: Hong Kong Dragon Airlines Ltd.' },
  { carrierCode: 'IR', airline: 'IR/IRA: Iran-Air' },
  { carrierCode: 'JL', airline: 'JL/JAL: Japan Airlines Co. Ltd.' },
  { carrierCode: 'EG', airline: 'EG/JAA: Japan Asia Airways Co. Ltd.' },
  { carrierCode: 'B6', airline: 'B6/JBU: JetBlue' },
  { carrierCode: 'KL', airline: 'KL/KLM: KLM Royal Dutch Airlines' },
  { carrierCode: 'KE', airline: 'KE/KAL: Korean Air Lines Co. Ltd.' },
  { carrierCode: 'LH', airline: 'LH/DLH: Lufthansa Cargo AG' },
  { carrierCode: 'MH', airline: 'MH/MAS: Malaysia Airlines System Berhad' },
  { carrierCode: 'OM', airline: 'OM/MHL: Miat-Mongolian Airlines' },
  { carrierCode: 'KZ', airline: 'KZ/NCA: Nippon Cargo Airlines' },
  { carrierCode: 'NW', airline: 'NW/NWA: Northwest Airlines, Inc.' },
  { carrierCode: 'PK', airline: 'PK/PIA: Pakistan Int\'l Airlines' },
  { carrierCode: 'PR', airline: 'PR/PAL: Philippine Airlines, Inc.' },
  { carrierCode: 'PO', airline: 'PO/PAC: Polar Air Cargo Inc.' },
  { carrierCode: 'QF', airline: 'QF/QFA: Qantas Airways Ltd.' },
  { carrierCode: 'RL', airline: 'RL/RNA: Royal Nepal Airlines Corp.' },
  { carrierCode: 'SK', airline: 'SK/SAS: Scandanavian Airways Systems' },
  { carrierCode: 'FM', airline: 'FM: Shanghai Airlines Co. Ltd.' },
  { carrierCode: 'SQ', airline: 'SQ/SQC: Singapore Airlines Ltd.' },
  { carrierCode: 'WN', airline: 'WN/SWA: Southwest Airlines' },
  { carrierCode: 'NK', airline: 'NK/NKS: Spirit Airlines' },
  { carrierCode: 'UL', airline: 'UL/ALK: Srilankan Airlines Ltd.' },
  { carrierCode: 'SY', airline: 'SY/SCX: Sun Country Airlines' },
  { carrierCode: 'LX', airline: 'LX/SWR: Swiss Int\'l Airlines Ltd.' },
  { carrierCode: 'TG', airline: 'TG/THA: Thai Airways Int\'l Public Co. Ltd.' },
  { carrierCode: 'TK', airline: 'TK/THY: Turkish Airlines Inc.' },
  { carrierCode: 'UA', airline: 'UA/UAL: United Airlines, Inc.' },
  { carrierCode: '5X', airline: '5X/UPS: United Parcel Service' },
  { carrierCode: 'HY', airline: 'HY/UZB: Uzbekistan Airways' },
  { carrierCode: 'VN', airline: 'VN/HVN: Vietnam Airlines' },
  { carrierCode: 'VS', airline: 'VS/VIR: Virgin Atlantic' },
];

export default AirlineCodeList;